### ISSUE TITLE
Redefine navargus package using pyproject.toml

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/nav-argus-glue#13]
navargus still uses `setup.py`/`setup.cfg` for its package definition. Its `pyproject.toml` only serves as a common configuration file for third party tools.

`setup.py`/`setup.cfg` should be removed in favor of using `pyproject.toml` only, in accordance with modern Python packaging practices.

**Comment by hmpf** [comment]
This doesn't even use setuptools_scm!

How-to!

1. Make sure you have `build` installed. On Debian that's the package `python3-build` but why not use [pipx](https://pypa.github.io/pipx/installation/) to install it to only just your own user.
2. Rename the existing pyproject.toml to something temporary
3. Make a package (`python setup.py sdist bdist_wheel`) and move the resulting packages away to safety.
4. Use for instance [ini2toml](https://github.com/abravalheri/ini2toml) to translate the `setup.cfg` to a `pyproject.toml`
5. Remove `setup.py` and `setup.cfg`
6. Make a new package (`python3 -m build` or `pyproject-build` depending on how you installed build)
7. Compare the packages from step 3) and 6), If the file contents are identical, you're done
8. Append the contents of the old `pyproject.toml`-file to the new one 
9. Commit!
